# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets: # Contient la liste des filtres
        miniature: # Nom du filtre
            quality: 75 # Qualité de l'image
            filters:
                thumbnail: # Filtre "Thumbnail"
                    size: [360, 230] # Taille de l'image de sortie
                    mode: outbound # Découpage de l'image
    
        test: # Nom du filtre
            quality: 75 # Qualité de l'image
            filters:
                scale: # Filtre "Thumbnail"
                    dim: [1200, 1200] # Taille de l'image de sortie
                    
            
                
                    
                    